deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
language: node_js
node_js:
  - "node"
  - "7"
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - npm run test
after_script:
  - yarn run deploy 
